// -*- mode: c++ -*-

#ifndef __script_events_h
#define __script_events_h

BEGIN_DECLARE_EVENT_TYPES()
// generated by object browser to create a new editor with script text
  DECLARE_EVENT_TYPE(PQWX_ScriptToWindow, -1)
// generated by editors to indicate they are selected
  DECLARE_EVENT_TYPE(PQWX_ScriptSelected, -1)
// send by frame to editor from menu bar
  DECLARE_EVENT_TYPE(PQWX_ScriptExecute, -1)
// generated by editors at start/stop of execution
  DECLARE_EVENT_TYPE(PQWX_ScriptExecutionBeginning, -1)
  DECLARE_EVENT_TYPE(PQWX_ScriptExecutionFinishing, -1)
// sent asynchronously by execution work when it completes
  DECLARE_EVENT_TYPE(PQWX_ScriptQueryComplete, -1)
END_DECLARE_EVENT_TYPES()

#define PQWX_SCRIPT_TO_WINDOW(id, fn) EVT_COMMAND(id, PQWX_ScriptToWindow, fn)
#define PQWX_SCRIPT_SELECTED(id, fn) EVT_COMMAND(id, PQWX_ScriptSelected, fn)
#define PQWX_SCRIPT_EXECUTE(id, fn) EVT_COMMAND(id, PQWX_ScriptExecute, fn)
#define PQWX_SCRIPT_QUERY_COMPLETE(id, fn) EVT_COMMAND(id, PQWX_ScriptQueryComplete, fn)
#define PQWX_SCRIPT_EXECUTION_BEGINNING(id, fn) EVT_COMMAND(id, PQWX_ScriptExecutionBeginning, fn)
#define PQWX_SCRIPT_EXECUTION_FINISHING(id, fn) EVT_COMMAND(id, PQWX_ScriptExecutingFinishing, fn)

#endif
